name: video_translator
description: A basic Flutter app to play movies and translate subtitles.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.1
  video_player: ^2.9.1

flutter:
  uses-material-design: true
